- name: Load defaults from other_role
  ansible.builtin.include_vars:
    file: '{{ role_path }}/../zsh-packages/defaults/main.yml'
    name: zsh-packages defaults

# - name: Debug zsh_user_config_dir
#   debug:
#     var: zsh_user_config_dir
- name: Detect devcontainer
  set_fact:
    is_devcontainer: >-
      {{
        lookup('env', 'REMOTE_CONTAINERS') == 'true' or
        lookup('env', 'VSCODE_REMOTE_CONTAINER') is defined or
        lookup('env', 'VSCODE_INJECTION') is defined or
        lookup('env', 'TERM_PROGRAM') == 'vscode'
      }}

- name: Rsync a directory from control to remote, merging (no deletes)
  ansible.builtin.copy:
    src: config/          # path on the Ansible control node (relative to role/playbook)
    dest: '{{ zsh_user_config_dir | trim }}/'          # directory on remote host
    owner: '{{ zsh_user }}'
    group: '{{ zsh_user }}'
    mode: '0644'
    directory_mode: "0755"
    force: false
  when: is_devcontainer


- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto
  
# - name: Check packages
#   debug:
#     var: ansible_facts.packages

- name: Copy zsh tool configs
  include_tasks: copy-config.yml
  loop: '{{ zsh_packages }}'
  loop_control:
    label: '{{ item }}'
  when: not is_devcontainer
# - name: Copy application files
#   copy:
#     src: files/config/          # relative to your playbook (or role’s files/)
#     dest: "{{ zsh_user_config_dir }}/"          # will create /etc/myapp/…
#     owner: "{{ zsh_user }}"
#     group: "{{ zsh_user }}"
#     mode: '0755'
#     force: no
# become: true
# - name: Ensure each export KEY=VALUE is present (replace or add)
#   lineinfile:
#     path: "{{ zsh_user_home }}/.aliases"
#     create: no              # we already touched above
#     regexp: '^export {{ item.key }}='
#     line: 'export {{ item.key }}={{ item.value }}'
#     backrefs: no
#   loop: "{{ bash_aliases_exports | dict2items }}"
#   loop_control:
#     label: "{{ item.key }}"

- name: Add bash aliases if package is installed
  ansible.builtin.lineinfile:
    path: '{{ zsh_user_home }}/.aliases'
    line: '{{ alias_entry.1 }}'
    create: true
    state: present
    owner: '{{ zsh_user }}'
    group: '{{ zsh_user }}'
    mode: '0644'
  loop: "{{ shell_aliases | dict2items | subelements('value') }}"
  loop_control:
    loop_var: alias_entry
    label: '{{ alias_entry.1 }}'
  when: 'alias_entry.0.key in ansible_facts.packages'

- name: Add bash exports if package is installed
  ansible.builtin.lineinfile:
    path: '{{ zsh_user_home }}/.aliases'
    line: 'export {{ alias_entry.1 }}'
    create: true
    state: present
    owner: '{{ zsh_user }}'
    group: '{{ zsh_user }}'
    mode: '0644'
  loop: "{{ shell_exports | dict2items | subelements('value') }}"
  loop_control:
    loop_var: alias_entry
    label: '{{ alias_entry.1 }}'
  when: 'alias_entry.0.key in ansible_facts.packages'
