- name: Set subdir for {{ item }}
  set_fact:
    subdir: '{{ zsh_packages_overrides[item] | default(item) }}'

- name: Stat config dir for {{ item }} on controller
  ansible.builtin.stat:
    path: '{{ role_path }}/files/config/{{ subdir }}/'
  delegate_to: localhost
  run_once: false
  register: src_stat
  ignore_errors: true

- name: Copy config/{{ subdir }}/ to user config
  ansible.builtin.copy:
    src: 'config/{{ subdir }}/'
    dest: '{{ zsh_user_config_dir | trim }}/{{ subdir }}/'
    owner: '{{ zsh_user }}'
    group: '{{ zsh_user }}'
    mode: '0644'
    force: false
  when:
    - item in ansible_facts.packages
    - src_stat.stat.exists
    - src_stat.stat.isdir | default(false)

# - name: Add bash exports if package is installed
#   ansible.builtin.lineinfile:
#     path: '{{ zsh_user_home }}/.aliases'
#     line: '{{  alias_entry.1 }}'
#     create: true
#     state: present
#     owner: '{{ zsh_user }}'
#     group: '{{ zsh_user }}'
#     mode: '0644'
#   loop: "{{ shell_aliases[item] | dict2items | subelements('value') }}"
#   loop_control:
#     loop_var: alias_entry
#     label: '{{ alias_entry.1 }}'
#   when:
#     - item in shell_aliases.keys()
# - name: Add bash exports if package is installed
#   ansible.builtin.lineinfile:
#     path: '{{ zsh_user_home }}/.aliases'
#     line: '{{  alias_entry.1 }}'
#     create: true
#     state: present
#     owner: '{{ zsh_user }}'
#     group: '{{ zsh_user }}'
#     mode: '0644'
#   loop: "{{ shell_exports | dict2items | subelements('value') }}"
#   loop_control:
#     loop_var: alias_entry
#     label: '{{ alias_entry.1 }}'
#   when: 'alias_entry.0.key in ansible_facts.packages'
# - name: Add bash exports if package is installed
#   ansible.builtin.lineinfile:
#     path: '{{ zsh_user_home }}/.aliases'
#     line: '{{  alias_entry.1 }}'
#     create: true
#     state: present
#     owner: '{{ zsh_user }}'
#     group: '{{ zsh_user }}'
#     mode: '0644'
#   loop: "{{ shell_aliases | dict2items | subelements('value') }}"
#   loop_control:
#     loop_var: alias_entry
#     label: '{{ alias_entry.1 }}'
#   when: 'alias_entry.0.key in ansible_facts.packages'

# - name: Add bash exports if package is installed
#   ansible.builtin.lineinfile:
#     path: '{{ zsh_user_home }}/.aliases'
#     line: '{{  alias_entry.1 }}'
#     create: true
#     state: present
#     owner: '{{ zsh_user }}'
#     group: '{{ zsh_user }}'
#     mode: '0644'
#   loop: "{{ shell_exports | dict2items | subelements('value') }}"
#   loop_control:
#     loop_var: alias_entry
#     label: '{{ alias_entry.1 }}'
#   when: 'alias_entry.0.key in ansible_facts.packages'
# - name: Add alias lines if package is installed
#   ansible.builtin.lineinfile:
#     path: '{{ zsh_user_home }}/.aliases'
#     line: '{{ alias_entry.1 }}'
#     create: true
#     state: present
#     owner: '{{ zsh_user }}'
#     group: '{{ zsh_user }}'
#     mode: '0644'
#   loop: "{{ shell_aliases | dict2items | subelements('value') }}"
#   loop_control:
#     loop_var: alias_entry
#     label: '{{ alias_entry.1 }}'
#   when: alias_entry.0.key in ansible_facts.packages

# - name: Add export lines if package is installed
#   ansible.builtin.lineinfile:
#     path: '{{ zsh_user_home }}/.aliases'
#     line: '{{ export_entry.1 }}'
#     create: true
#     state: present
#     owner: '{{ zsh_user }}'
#     group: '{{ zsh_user }}'
#     mode: '0644'
#   loop: "{{ shell_exports | dict2items | subelements('value') }}"
#   loop_control:
#     loop_var: export_entry
#     label: '{{ export_entry.1 }}'
#   when: export_entry.0.key in ansible_facts.packages
