---
- name: Print the host’s FQDN
  debug:
    msg: "FQDN is {{ ansible_facts['fqdn'] }}"

- name: show Home dir
  debug:
    msg: "Home directory for {{ zsh_user }} is {{ zsh_user_home }}"

- name: Ensure .config directory exists
  file:
    path: '{{ zsh_user_config_dir }}'
    state: directory
    owner: '{{ zsh_user }}'
    group: '{{ zsh_user }}'
    mode: '0755'
  become: true
  become_user: '{{ zsh_user }}'

- name: Improve apt parallism
  ansible.builtin.blockinfile:
    path: '/etc/apt/apt.conf.d/99-parallel'
    block: |
      APT::Acquire::Retries "3";
      Acquire::http::Pipeline-Depth "0";
      Acquire::https::Pipeline-Depth "0";
      APT::Get::Max-Downloads "16";
      APT::Install-Recommends "false";
    state: present
  become: true
  failed_when: false
  become_user: root
  when: ansible_facts['pkg_mgr'] == 'apt'
